name: splitter
description: Cross-platform money-splitting app to organize your travels and apartments money

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  font_awesome_flutter: ^8.0.1
  bloc_pattern: ^1.3.0
  rxdart: ^0.20.0
  tuple: ^1.0.2
  flutter_secure_storage: ^3.1.2
  side_header_list_view: "^0.0.4"
  intl: any

flutter:

  uses-material-design: true

  assets:
      - assets/img/login_logo.png
      - assets/icon.png
      - assets/profile.png

  fonts:
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf
